sudo: false
language: rust

rust:
  - nightly
  - stable
os:
  - linux
  - osx

script:
  - cargo new libmiew --lib
  - ln -n mod.rs libmiew/src/ffi.rs
  - cd libmiew
  - echo "libc = \"0.2\"" >> Cargo.toml
  - echo "extern crate libc; mod ffi;" > src/lib.rs
  - cargo build
