---
sudo: false
language: c
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686

script:
  - gcc  -Wall -Wextra -Werror neko.h

addons:
  apt:
    packages:
      - gcc-multilib
